/// CYKEL — Directions Service
/// Uses OSRM public API (cycling/bike + foot profiles). Free, no API key required.
/// https://routing.openstreetmap.de

import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:flutter_polyline_points/flutter_polyline_points.dart';
import 'package:http/http.dart' as http;
import '../domain/route_result.dart';

/// Determines which OSRM profile is used for routing.
/// • [fastest] — `routed-bike`: most direct cycling route.
/// • [safest]  — `routed-foot`: pedestrian-safe paths, quieter roads.
/// • [effortOptimized] — `routed-bike` + wind scoring: pick the alternative
///   with the best net headwind score (Premium feature).
enum RouteMode { fastest, safest, effortOptimized }

class DirectionsService {
  // routing.openstreetmap.de/routed-bike uses real cycling speed profiles.
  // routed-foot uses pedestrian paths (quieter streets = safer for cycling).
  static String _baseForMode(RouteMode mode) => switch (mode) {
        RouteMode.fastest           => 'https://routing.openstreetmap.de/routed-bike/route/v1/driving',
        RouteMode.safest            => 'https://routing.openstreetmap.de/routed-foot/route/v1/driving',
        RouteMode.effortOptimized   => 'https://routing.openstreetmap.de/routed-bike/route/v1/driving',
      };

  final PolylinePoints _polylinePoints = PolylinePoints();

  /// Returns up to 2 route alternatives (index 0 = primary/fastest).
  ///
  /// Pass [viaWaypoints] to add intermediate stops (in visit order).
  /// OSRM supports multi-leg routes: the steps and polylines from every
  /// leg are merged into a single [RouteResult].
  /// Note: OSRM only returns alternatives for simple 2-point routes;
  /// with waypoints only one result is returned.
  ///
  /// Supply [instructionBuilder] to produce locale-aware instruction strings.
  /// If omitted, English strings are generated by [_buildInstruction].
  Future<List<RouteResult>> getRoutes({
    required LatLng origin,
    required LatLng destination,
    List<LatLng>? viaWaypoints,
    RouteMode mode = RouteMode.fastest,
    String Function(String type, String modifier, String name)? instructionBuilder,
  }) async {
    try {
      // OSRM uses lon,lat ordering
      final coordParts = [
        '${origin.longitude},${origin.latitude}',
        ...?viaWaypoints?.map((wp) => '${wp.longitude},${wp.latitude}'),
        '${destination.longitude},${destination.latitude}',
      ];
      final coords = coordParts.join(';');
      // Alternatives only make sense for 2-point routes.
      final hasWaypoints = viaWaypoints != null && viaWaypoints.isNotEmpty;
      final uri = Uri.parse('${_baseForMode(mode)}/$coords').replace(queryParameters: {
        'overview': 'full',
        'geometries': 'polyline',
        'steps': 'true',
        'annotations': 'false',
        'alternatives': hasWaypoints ? 'false' : 'true',
      });

      final response = await http.get(uri, headers: {'User-Agent': 'CYKELApp/1.0'});
      if (response.statusCode != 200) {
        debugPrint('OSRM HTTP ${response.statusCode}: ${response.body}');
        return [];
      }

      final data = json.decode(response.body) as Map<String, dynamic>;
      if (data['code'] != 'Ok') {
        debugPrint('OSRM error: ${data['code']} — ${data['message'] ?? ''}');
        return [];
      }

      final routes = data['routes'] as List;
      if (routes.isEmpty) return [];

      final List<RouteResult> results = [];
      for (final rawRoute in routes) {
        final r = _parseRoute(
          rawRoute as Map<String, dynamic>,
          origin,
          destination,
          instructionBuilder,
        );
        if (r != null) results.add(r);
      }
      return results;
    } catch (e, st) {
      debugPrint('DirectionsService error: $e\n$st');
      return [];
    }
  }

  /// Convenience: returns the primary route, or null if none found.
  Future<RouteResult?> getRoute({
    required LatLng origin,
    required LatLng destination,
    List<LatLng>? viaWaypoints,
    RouteMode mode = RouteMode.fastest,
    String Function(String type, String modifier, String name)? instructionBuilder,
  }) async {
    final list = await getRoutes(
        origin: origin,
        destination: destination,
        viaWaypoints: viaWaypoints,
        mode: mode,
        instructionBuilder: instructionBuilder);
    return list.isEmpty ? null : list.first;
  }

  RouteResult? _parseRoute(
      Map<String, dynamic> route,
      LatLng origin,
      LatLng destination,
      String Function(String type, String modifier, String name)? instructionBuilder) {
    try {
      // Decode overview polyline
      final encodedPolyline = route['geometry'] as String;
      final decoded = _polylinePoints.decodePolyline(encodedPolyline);
      final polylinePoints =
          decoded.map((p) => LatLng(p.latitude, p.longitude)).toList();

      final totalDistance = (route['distance'] as num).toInt();
      final totalDuration = (route['duration'] as num).toInt();

      final legs = route['legs'] as List;
      if (legs.isEmpty) return null;

      // Merge steps from ALL legs (supports multi-stop routes).
      final steps = <RouteStep>[];
      for (final rawLeg in legs) {
        final leg      = rawLeg as Map<String, dynamic>;
        final stepsRaw = leg['steps'] as List? ?? [];
        for (final s in stepsRaw) {
          final step     = s as Map<String, dynamic>;
          final maneuver = step['maneuver'] as Map<String, dynamic>;
          final loc      = maneuver['location'] as List; // [lon, lat]
          final type     = maneuver['type'] as String? ?? '';
          final modifier = maneuver['modifier'] as String? ?? '';
          final name     = step['name'] as String? ?? '';
          final instruction = instructionBuilder != null
              ? instructionBuilder(type, modifier, name)
              : _buildInstruction(type, modifier, name);
          final endLoc = LatLng(
            (loc[1] as num).toDouble(),
            (loc[0] as num).toDouble(),
          );
          steps.add(RouteStep(
            instruction:     instruction,
            distanceMeters:  (step['distance'] as num).toInt(),
            durationSeconds: (step['duration'] as num).toInt(),
            startLocation:   endLoc,
            endLocation:     endLoc,
            maneuver: modifier.isNotEmpty ? '$type-$modifier' : type,
          ));
        }
      }

      // Fix endLocations: each step's endLocation = next step's startLocation
      for (var i = 0; i < steps.length - 1; i++) {
        steps[i] = RouteStep(
          instruction: steps[i].instruction,
          distanceMeters: steps[i].distanceMeters,
          durationSeconds: steps[i].durationSeconds,
          startLocation: steps[i].startLocation,
          endLocation: steps[i + 1].startLocation,
          maneuver: steps[i].maneuver,
        );
      }

      // Last step must end exactly at the requested destination coordinate.
      if (steps.isNotEmpty) {
        final last = steps.last;
        steps[steps.length - 1] = RouteStep(
          instruction: last.instruction,
          distanceMeters: last.distanceMeters,
          durationSeconds: last.durationSeconds,
          startLocation: last.startLocation,
          endLocation: destination,
          maneuver: last.maneuver,
        );
      }

      return RouteResult(
        polylinePoints: polylinePoints,
        distanceMeters: totalDistance,
        durationSeconds: totalDuration,
        steps: steps,
        originAddress: '',
        destinationAddress: '',
      );
    } catch (e) {
      debugPrint('_parseRoute error: $e');
      return null;
    }
  }

  String _buildInstruction(String type, String modifier, String name) {
    final on = name.isNotEmpty ? ' onto $name' : '';
    final on2 = name.isNotEmpty ? ' on $name' : '';
    switch (type) {
      case 'depart':
        return 'Head ${modifier.isNotEmpty ? modifier : 'forward'}$on2';
      case 'arrive':
        return 'You have arrived${name.isNotEmpty ? ' at $name' : ''}';
      case 'turn':
        return 'Turn $modifier$on';
      case 'new name':
        return 'Continue$on';
      case 'merge':
        return 'Merge$on';
      case 'fork':
        return 'Keep $modifier at the fork$on';
      case 'end of road':
        return 'Turn $modifier at end of road$on';
      case 'roundabout':
      case 'rotary':
        return 'Enter the roundabout${name.isNotEmpty ? ' — $name' : ''}';
      case 'exit roundabout':
      case 'exit rotary':
        return 'Exit the roundabout$on';
      case 'use lane':
        return 'Use the $modifier lane$on';
      default:
        return name.isNotEmpty ? 'Continue on $name' : 'Continue';
    }
  }
}

final directionsServiceProvider =
    Provider<DirectionsService>((ref) => DirectionsService());
